[33mWARNING [0m urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002081D848970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/65563868f55a6f84c6e9389efbd0154b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002081D872AC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/65563868f55a6f84c6e9389efbd0154b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:751 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002081D87F760>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/65563868f55a6f84c6e9389efbd0154b