{"uuid": "169f0e0b-5a69-4d02-bd56-c26b99a5c956", "children": ["14b4b860-a5b2-4432-a2fb-525a79013656"], "befores": [{"name": "_UnitTestCase__pytest_class_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=86.0.4240.75)\n\n", "trace": "  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\unittest.py\", line 131, in fixture\n    setup()\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\SampleFramework\\Test\\Login.py\", line 24, in setUpClass\n    cls.driver.get('https://opensource-demo.orangehrmlive.com/')\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Launch site", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=86.0.4240.75)\n\n", "trace": "  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\SampleFramework\\Test\\Login.py\", line 24, in setUpClass\n    cls.driver.get('https://opensource-demo.orangehrmlive.com/')\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Program Files\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1602923466946, "stop": 1602923472461}], "start": 1602923466946, "stop": 1602923472504}], "start": 1602923466946, "stop": 1602923472627}